/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.controlevenda.view.consulta;

import com.mycompany.controlevenda.constants.model.VendaConstants;
import com.mycompanyy.controlevenda.dto.VendaPorGrupoDTO;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author gabri
 */
public class VendasPorGrupoView extends JFrame {

    private List<VendaPorGrupoDTO> vendasGrupo = null;

    /**
     * Creates new form VendaPorCliente
     *
     * @param vendasGrupo
     */
    public VendasPorGrupoView(List<VendaPorGrupoDTO> vendasGrupo) {
        initComponents();

        if (vendasGrupo.stream().anyMatch(vendaGrupo
                        -> vendaGrupo.getTipo() == VendaPorGrupoDTO.CLIENTE)){
            setTitle(VendaConstants.VENDA_POR_CLIENTE);
        }
        else {
            setTitle(VendaConstants.VENDA_POR_PRODUTO);
        }

        this.vendasGrupo = vendasGrupo;

        configuraTabela();
        preencheTable();
    }

    /**
     * Configura as informações que vão aparecer na Table.
     */
    private void configuraTabela() {
        tableConsulta.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        DefaultTableModel tableModelVenda = new DefaultTableModel() {

            /**
             * {@inheritDoc}
             */
            @Override
            public boolean isCellEditable(final int row, final int column) {
                return false;
            }
        };

        if ((!vendasGrupo.isEmpty() || vendasGrupo != null)
                && vendasGrupo.stream().anyMatch(vendaGrupo
                        -> vendaGrupo.getTipo() == VendaPorGrupoDTO.CLIENTE)) {
            tableModelVenda.addColumn("Cliente");
        } else {
            tableModelVenda.addColumn("Produto");
        }

        tableModelVenda.addColumn("Total Vendas");

        tableConsulta.setModel(tableModelVenda);

        //Define o tamanho das colunas do JTable.
        TableColumnModel tableColumnModelVenda
                = tableConsulta.getColumnModel();

        tableColumnModelVenda.getColumn(0).setPreferredWidth(350);
        tableColumnModelVenda.getColumn(1).setPreferredWidth(100);

        //Define que os registros irão aparecer centralizados.
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < tableColumnModelVenda.getColumnCount(); i++) {
            tableColumnModelVenda.getColumn(i).setCellRenderer(cellRenderer);
        }
    }

    /**
     * Preenche a tabela presente em tela.
     */
    private void preencheTable() {
        DefaultTableModel tableModelVenda
                = (DefaultTableModel) tableConsulta.getModel();
        tableModelVenda.setNumRows(0);

        for (VendaPorGrupoDTO vendaGrupo : vendasGrupo) {
            tableModelVenda.addRow(new Object[]{
                vendaGrupo.getNome(),
                vendaGrupo.getValorTotalVenda().toString(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableConsulta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableConsulta);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableConsulta;
    // End of variables declaration//GEN-END:variables
}
