package com.mycompany.controlevenda.view;

import com.mycompany.controlevenda.constants.TitulosConstants;
import com.mycompany.controlevenda.constants.model.ClienteConstants;
import com.mycompany.controlevenda.constants.model.ProdutoConstants;
import com.mycompany.controlevenda.constants.model.VendaConstants;
import com.mycompany.controlevenda.control.VendaController;
import com.mycompany.controlevenda.view.cliente.PrincipalClienteView;
import com.mycompany.controlevenda.view.consulta.VendasPorGrupoView;
import com.mycompany.controlevenda.view.produto.PrincipalProdutoView;
import com.mycompany.controlevenda.view.venda.PrincipalVendaView;
import javax.swing.JFrame;

public class TelaPrincipal extends JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();

        setTitle(TitulosConstants.CONTROLE_VENDA);
        menuItemProduto.setText(ProdutoConstants.PRODUTO);
        menuItemVenda.setText(VendaConstants.VENDA);
        menuItemCliente.setText(ClienteConstants.CLIENTE);
        menuItemVendaPorCliente.setText(VendaConstants.VENDA_POR_CLIENTE);
        menuItemVendaPorProduto.setText(VendaConstants.VENDA_POR_PRODUTO);

        menuItemCliente.addActionListener(menu -> listagemCliente());
        menuItemProduto.addActionListener(menu -> listagemProduto());
        menuItemVenda.addActionListener(menu -> listagemVenda());

        menuItemVendaPorCliente.addActionListener(
                menu -> consultaVendaPorCliente(1));
        menuItemVendaPorProduto.addActionListener(
                menu -> consultaVendaPorCliente(2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemCliente = new javax.swing.JMenuItem();
        menuItemProduto = new javax.swing.JMenuItem();
        menuItemVenda = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();
        menuItemVendaPorCliente = new javax.swing.JMenuItem();
        menuItemVendaPorProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de vendas");
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jMenu1.setText("Cadastro");

        menuItemCliente.setText("Cliente");
        jMenu1.add(menuItemCliente);

        menuItemProduto.setText("Produto");
        jMenu1.add(menuItemProduto);

        menuItemVenda.setText("Venda");
        jMenu1.add(menuItemVenda);

        menuPrincipal.add(jMenu1);

        menuConsulta.setText("Consulta");

        menuItemVendaPorCliente.setText("menuItemVendaPorCliente");
        menuConsulta.add(menuItemVendaPorCliente);

        menuItemVendaPorProduto.setText("menuItemVendaPorProduto");
        menuConsulta.add(menuItemVendaPorProduto);

        menuPrincipal.add(menuConsulta);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Chama a listagem de Cliente.
     */
    private void listagemCliente() {
        PrincipalClienteView principalClienteView = new PrincipalClienteView();
        principalClienteView.setVisible(true);
    }

    /**
     * Chama a listagem de Produto.
     */
    private void listagemProduto() {
        PrincipalProdutoView principalProdutoView = new PrincipalProdutoView();
        principalProdutoView.setVisible(true);
    }

    private void listagemVenda() {
        PrincipalVendaView principalVendaView = new PrincipalVendaView();
        principalVendaView.setVisible(true);
    }

    private void consultaVendaPorCliente(int consultaSelecionada) {
        VendaController vendaController = new VendaController();

        switch (consultaSelecionada) {
            case 1: {
                VendasPorGrupoView vendaPorClienteView = new VendasPorGrupoView(
                        vendaController.retornaVendaPorCliente()
                );
                vendaPorClienteView.setVisible(true);
                break;
            }

            case 2: {
                VendasPorGrupoView vendaPorClienteView = new VendasPorGrupoView(
                        vendaController.retornaVendaPorProduto()
                );
                vendaPorClienteView.setVisible(true);
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenuItem menuItemCliente;
    private javax.swing.JMenuItem menuItemProduto;
    private javax.swing.JMenuItem menuItemVenda;
    private javax.swing.JMenuItem menuItemVendaPorCliente;
    private javax.swing.JMenuItem menuItemVendaPorProduto;
    private javax.swing.JMenuBar menuPrincipal;
    // End of variables declaration//GEN-END:variables
}
